### ISSUE TITLE
7.0.11 is too old

### ISSUE THREAD

**Issue by chuisiniyo** [nitrogen-project/android_external_libphonenumber#1]
did this repository still working now?
libphonenumber version 7.0.11 is too old
google has update the data to v8.3.2
anyone update this,please.

**Comment by xyyx** [comment]
https://android.googlesource.com/platform/external/libphonenumber/+log/a2958e2a0fadcf63688029b7e6b0ccc5732222a2

Where?)

**Comment by chuisiniyo** [comment]
sorry i didn't see it, but i found a new version at https://github.com/googlei18n/libphonenumber , what's the difference ?
